interface words {
  word: string;
  desc: string;
}

export const wordLibrary: words[] = [
  { word: "apple", desc: "A common red or green fruit" },
  { word: "banana", desc: "A long yellow tropical fruit" },
  { word: "guitar", desc: "A musical instrument with strings" },
  { word: "pencil", desc: "Used for writing or drawing" },
  { word: "elephant", desc: "The largest land animal" },
  { word: "mountain", desc: "A large natural elevation of earth" },
  { word: "river", desc: "A large flowing body of water" },
  { word: "school", desc: "A place where students learn" },
  { word: "teacher", desc: "A person who helps students learn" },
  { word: "computer", desc: "An electronic device used for computing" },
  { word: "keyboard", desc: "Used to type letters on a computer" },
  { word: "mouse", desc: "A small device used to control a computer" },
  { word: "bottle", desc: "Used to hold liquids" },
  { word: "window", desc: "An opening in a wall with glass" },
  { word: "table", desc: "A piece of furniture with a flat top" },
  { word: "chair", desc: "You sit on it" },
  { word: "mirror", desc: "Used to see your reflection" },
  { word: "rocket", desc: "Flies into space" },
  { word: "planet", desc: "Orbits around a star" },
  { word: "cloud", desc: "White and fluffy in the sky" },
  { word: "rainbow", desc: "Colorful arc in the sky after rain" },
  { word: "pyramid", desc: "Famous ancient structure in Egypt" },
  { word: "desert", desc: "Dry land with very little rain" },
  { word: "ocean", desc: "A huge body of saltwater" },
  { word: "island", desc: "Land surrounded by water" },
  { word: "bridge", desc: "Structure that connects two places" },
  { word: "train", desc: "A long vehicle that runs on tracks" },
  { word: "bicycle", desc: "Has two wheels and is powered by pedals" },
  { word: "airplane", desc: "Flies in the sky and carries passengers" },
  { word: "carpet", desc: "Covers the floor" },
  { word: "lamp", desc: "Gives light in a room" },
  { word: "camera", desc: "Used to take photos" },
  { word: "watch", desc: "Tells you the time and worn on wrist" },
  { word: "phone", desc: "Used to call or text someone" },
  { word: "garden", desc: "Place where plants or flowers grow" },
  { word: "forest", desc: "Large area covered with trees" },
  { word: "butterfly", desc: "An insect with colorful wings" },
  { word: "spider", desc: "Has eight legs and spins webs" },
  { word: "lion", desc: "Known as the king of the jungle" },
  { word: "zebra", desc: "Striped black and white animal" },
  { word: "tiger", desc: "Big cat with orange fur and black stripes" },
  { word: "monkey", desc: "A playful animal that climbs trees" },
  { word: "penguin", desc: "A bird that cannot fly but swims" },
  { word: "shark", desc: "A dangerous fish with sharp teeth" },
  { word: "whale", desc: "The largest animal in the ocean" },
  { word: "pizza", desc: "Popular Italian food with cheese and toppings" },
  { word: "sandwich", desc: "Two pieces of bread with filling" },
  { word: "chocolate", desc: "A sweet treat made from cocoa" },
  { word: "icecream", desc: "Cold dessert usually eaten in summer" },
  { word: "hamburger", desc: "Fast food with bun and meat" },
];

export const winMessages: string[] = [
  "Awesome 🎉",
  "Genius 🧠",
  "Superb 👏",
  "Fantastic 🌟",
  "Excellent ✅",
  "Brilliant 💡",
  "Outstanding 🔥",
  "Impressive 🚀",
  "Wonderful 💎",
  "Legendary 🏆",
  "Amazing ✨",
  "You Rock 🤘",
  "Champion 🥇",
  "Marvelous 🎊",
  "Terrific 🎯",
];

export const loseMessages: string[] = [
  "Oops! Better luck next time",
  "The hangman got you",
  "Close call, but not enough",
  "Don’t give up, try again",
  "Missed it!",
  "Game Over",
  "Almost there… but no",
  "That was tough!",
  "Keep practicing",
  "Not your day",
  "You got hanged",
  "Try harder next time",
  "Better sharpen your guessing skills",
  "Word slipped away",
  "Sad trombone sound",
];
